services:
  database:
    image: postgres:15
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - battle-psql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
  redis:
    image: redis:7
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - redis-data:/data
  mercure:
    image: dunglas/mercure
    environment:
      # Uncomment the following line to disable HTTPS
      SERVER_NAME: ':1337'
      MERCURE_PUBLISHER_JWT_KEY: 'ChangeMe'
      MERCURE_SUBSCRIBER_JWT_KEY: 'ChangeMe'
      MERCURE_EXTRA_DIRECTIVES: |-
        cors_origins http://localhost:3333
    command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
    ports:
      - '1337:1337'
    volumes:
      - mercure_data:/data
      - mercure_config:/config
volumes:
  battle-psql-data:
  redis-data:
  mercure_data:
  mercure_config:
